name: 'Test report'
on: 
  workflow_run:
    workflows: ['Validate actions']
    types:
      - completed
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install jest
              run: |
                  npm i -g jest
            - name: Run jest and generate coverage report
              run: |
                  jest
            - name: Setup LCOV
              uses: hrishikesh-kadam/setup-lcov@v1