name: 'Test report'
on: 
  workflow_run:
    workflows: ['Validate actions']
    types:
      - completed
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/test-reporter@v1
              with:
                artifact: test-results            # artifact name
                name: JEST Tests                  # Name of the check run which will be created
                path: '*.xml'                     # Path to test results (inside artifact .zip)
                reporter: jest-junit              # Format of test results