name: Validate actions
on: [push]
jobs:
  validate-actions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install BB CLI
        run: |
            npm i -g @betty-blocks/cli
      -
        name: Run validation
        run: |
            bb functions validate        
