name: CI
on: [push]
jobs:
  validate-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Install BB CLI
        run: |
            npm i -g @betty-blocks/cli
      -
        name: Install the included npm packages
        run: |
            npm ci
      -
        name: Run validation
        run: |
            bb functions validate
  coverage:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Install dependencies
            run: |
                npm ci && npm i -g jest
          - name: Run jest and generate coverage report
            run: |
                jest
          - name: Setup LCOV
            uses: hrishikesh-kadam/setup-lcov@v1
          - name: Report code coverage
            uses: zgosalvez/github-actions-report-lcov@v3
            with:
              coverage-files: coverage/lcov.*.info
              minimum-coverage: 90
              artifact-name: code-coverage-report
              github-token: ${{ secrets.GITHUB_TOKEN }}
              working-directory: apps/my-first-app
